### ISSUE TITLE
能不能用sqlite数据库？

### ISSUE THREAD

**Issue by zhangminghao1989** [manier13579/GABS-AddressBookSystem#4]
能不能用sqlite数据库？
mysql实在太占资源了。

**Comment by manier13579** [comment]
你好~  谢谢留言，我也觉得sqlite很适合这个项目。当初用mysql只是因为有现有的数据库可用。等我有空的时候会考虑写一下sqlite版本，你也可以自行开发~

**Comment by manier13579** [comment]
robotwu66 已贡献sqlite数据文件
